MainCraft:
  azuazu3939: #Item
    azuriter: #Item2
      a:
        Item:
      b:
        Item:
      c:
        Item:
      d:
        Item:
      e:
        Item:
      f:
        Item:
      g:
        Item:
      h:
        Item:
      i:
        Item:
      end:
        Item:
      Item:
    Item:
